export interface College {
  id: string
  name: string
  state: string
  city: string
  naac: string
  bsccEligible: boolean
  featured: boolean
  courses: string[]
  fees: string
  highlights: string[]
  website?: string
  hostel?: string
  mess?: string
}

export const COLLEGES: College[] = [
  {
    id: "aditya-group-of-institutions",
    name: "Aditya Group of Institutions",
    state: "Andhra Pradesh",
    city: "Visakhapatnam",
    naac: "A",
    bsccEligible: true,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["6 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "ambalika-group-of-institutions",
    name: "Ambalika Group of Institutions",
    state: "UP",
    city: "Lucknow",
    naac: "A",
    bsccEligible: true,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["NAAC A accredited", "B.Tech and MBA available", "BSCC Eligible"],
  },
  {
    id: "amritsar-group-of-colleges",
    name: "Amritsar Group of Colleges",
    state: "Punjab",
    city: "Amritsar",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Sc Nursing", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["13 courses available", "B.Sc Nursing and B.Pharma", "BSCC Eligible"],
  },
  {
    id: "bhai-gurdas-group-of-institutions",
    name: "Bhai Gurdas Group of Institutions",
    state: "Punjab",
    city: "Sangrur",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Sc Agriculture", "B.Sc Nursing", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["9 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "cv-raman-global-university",
    name: "CV Raman Global University",
    state: "Bihar",
    city: "Hajipur",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["5 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "champaran-college",
    name: "Champaran College",
    state: "Bihar",
    city: "Bettiah",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["BBA", "BCA/MCA"],
    fees: "Consult CAE for fees",
    highlights: ["4 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "christian-college-of-engineering-technol",
    name: "Christian College of Engineering & Technology",
    state: "Chhattisgarh",
    city: "Raipur",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["5 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "dbs-global-university",
    name: "DBS Global University",
    state: "Uttarakhand",
    city: "Dehradun",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Sc Agriculture", "B.Sc Nursing", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["16 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "datta-meghe-group-of-institutions",
    name: "Datta Meghe Group of Institutions",
    state: "Maharashtra",
    city: "Wardha",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Pharma", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA", "MBBS India"],
    fees: "Consult CAE for fees",
    highlights: ["7 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "desh-bhagat-university",
    name: "Desh Bhagat University",
    state: "Punjab",
    city: "Mandi Gobindgarh",
    naac: "A",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Sc Nursing", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["8 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "dhanarwala-group",
    name: "Dhanarwala Group",
    state: "Bihar",
    city: "Patna",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["3 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "exalt-group-of-institutions",
    name: "Exalt Group of Institutions",
    state: "Bihar",
    city: "Vaishali",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["5 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "ggi-gulzar-group-of-institutions",
    name: "GGI – Gulzar Group of Institutions",
    state: "Punjab",
    city: "Ludhiana",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["8 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "gniot-group-of-institutions",
    name: "GNIOT Group of Institutions",
    state: "UP",
    city: "Greater Noida",
    naac: "A+",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Sc Nursing", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "₹1,80,000/year (B.Tech CSE)",
    highlights: ["B.Tech ME/ECE/CE: ₹1,20,000/year", "MBA: ₹2,50,000/year", "BSCC Eligible"],
    website: "https://www.gniotgroup.edu.in",
  },
  {
    id: "galgotias-university",
    name: "Galgotias University",
    state: "UP",
    city: "Greater Noida",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Pharma", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["9 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "gandhi-institute-for-technology-gift",
    name: "Gandhi Institute for Technology (GIFT)",
    state: "Odisha",
    city: "Bhubaneswar",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Sc Agriculture", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["8 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "ganga-institute-of-technology-management",
    name: "Ganga Institute of Technology & Management (GITAM)",
    state: "Haryana",
    city: "Rohtak",
    naac: "A+",
    bsccEligible: true,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["8 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "ganpat-university",
    name: "Ganpat University",
    state: "Gujarat",
    city: "Mehsana",
    naac: "A",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Sc Agriculture", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["13 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "global-group-of-institutes",
    name: "Global Group of Institutes",
    state: "Punjab",
    city: "Amritsar",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["7 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "global-institute-of-technology",
    name: "Global Institute of Technology",
    state: "West Bengal",
    city: "Kolkata",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["6 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "gokul-global-university",
    name: "Gokul Global University",
    state: "Gujarat",
    city: "Siddhpur",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Sc Agriculture", "B.Sc Nursing", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["17 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "guru-kashi-university",
    name: "Guru Kashi University",
    state: "Punjab",
    city: "Bathinda",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Sc Nursing", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["20 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "hmr-institute-of-technology-and-manageme",
    name: "HMR Institute of Technology and Management",
    state: "Delhi",
    city: "Delhi",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["6 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "haldia-institute-of-technology",
    name: "Haldia Institute of Technology",
    state: "West Bengal",
    city: "Kolkata",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["5 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "haridwar-university",
    name: "Haridwar University",
    state: "Uttarakhand",
    city: "Roorkee",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Sc Agriculture", "B.Sc Nursing", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["19 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "himalaya-group-of-institutions",
    name: "Himalaya Group of Institutions",
    state: "Bihar",
    city: "Patna",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["5 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "hindustan-college-of-science-technology",
    name: "Hindustan College of Science & Technology",
    state: "UP",
    city: "Mathura",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["13 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "ies-group",
    name: "IES Group",
    state: "MP",
    city: "Bhopal",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["6 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "iimt-university",
    name: "IIMT University",
    state: "UP",
    city: "Meerut",
    naac: "A",
    bsccEligible: true,
    featured: false,
    courses: ["B.Sc Agriculture", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["17 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "invertis-university",
    name: "Invertis University",
    state: "UP",
    city: "Bareilly",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "From ₹55,000/year",
    highlights: ["Affordable fees", "Multiple Streams", "BSCC Eligible"],
  },
  {
    id: "jbit-group-of-institutions",
    name: "JBIT Group of Institutions",
    state: "Uttarakhand",
    city: "Dehradun",
    naac: "A",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Sc Agriculture", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["12 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "jagannath-university",
    name: "Jagannath University",
    state: "Rajasthan",
    city: "Jaipur",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["7 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "jain-university",
    name: "Jain University",
    state: "Karnataka",
    city: "Bangalore",
    naac: "A+",
    bsccEligible: true,
    featured: true,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "From ₹2,00,000/year",
    highlights: ["NAAC A+ rated", "Strong placement record", "BSCC Eligible"],
    website: "https://www.jainuniversity.ac.in",
  },
  {
    id: "jaipur-national-university",
    name: "Jaipur National University",
    state: "Rajasthan",
    city: "Jaipur",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Sc Agriculture", "B.Sc Nursing", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["18 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "kl-university",
    name: "KL University",
    state: "Andhra Pradesh",
    city: "Vijayawada",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Pharma", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["8 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "khalsa-college-of-engineering-technology",
    name: "Khalsa College of Engineering & Technology",
    state: "Punjab",
    city: "Amritsar",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Sc Agriculture", "B.Sc Nursing", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["17 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "lnct-group-of-colleges",
    name: "LNCT Group of Colleges",
    state: "MP",
    city: "Bhopal",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Pharma", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["8 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "lovely-professional-university-lpu",
    name: "Lovely Professional University (LPU)",
    state: "Punjab",
    city: "Phagwara",
    naac: "A+",
    bsccEligible: true,
    featured: true,
    courses: ["B.Pharma", "B.Sc Agriculture", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "From ₹1,50,000/year",
    highlights: ["30,000+ students placed/year", "600+ industry partners", "BSCC Eligible"],
    website: "https://www.lpu.in",
  },
  {
    id: "mnm-institute-of-management",
    name: "MNM Institute of Management",
    state: "Bihar",
    city: "Patna",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["3 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "ms-ramaiah-institute-of-technology",
    name: "MS Ramaiah Institute of Technology",
    state: "Karnataka",
    city: "Bangalore",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Tech / Engineering", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["5 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "maharishi-markandeshwar-university-mmu",
    name: "Maharishi Markandeshwar University (MMU)",
    state: "Haryana",
    city: "Ambala",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA", "MBBS India"],
    fees: "Consult CAE for fees",
    highlights: ["9 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "manav-rachna-international-institute-mri",
    name: "Manav Rachna International Institute (MRIIRS)",
    state: "Haryana",
    city: "Faridabad",
    naac: "A+",
    bsccEligible: true,
    featured: false,
    courses: ["BBA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["10 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "manav-rachna-university-mru",
    name: "Manav Rachna University (MRU)",
    state: "Haryana",
    city: "Faridabad",
    naac: "A+",
    bsccEligible: true,
    featured: false,
    courses: ["B.Sc Nursing", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["19 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "mangalayatan-university",
    name: "Mangalayatan University",
    state: "UP",
    city: "Aligarh",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Sc Agriculture", "B.Sc Nursing", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["16 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "mangalmay-group-of-institutions",
    name: "Mangalmay Group of Institutions",
    state: "UP",
    city: "Greater Noida",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["9 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "marwadi-university",
    name: "Marwadi University",
    state: "Gujarat",
    city: "Rajkot",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Pharma", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["7 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "mewar-university",
    name: "Mewar University",
    state: "Rajasthan",
    city: "Chittorgarh",
    naac: "A",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Sc Agriculture", "B.Sc Nursing", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["20 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "niet-noida-institute-of-engineering-tech",
    name: "NIET – Noida Institute of Engineering & Technology",
    state: "UP",
    city: "Greater Noida",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Pharma", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["8 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "nandi-group-of-institutions",
    name: "Nandi Group of Institutions",
    state: "Odisha",
    city: "Bhubaneswar",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["6 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "navrachana-university",
    name: "Navrachana University",
    state: "Gujarat",
    city: "Vadodara",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["5 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "noida-international-university",
    name: "Noida International University",
    state: "UP",
    city: "Greater Noida",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Pharma", "B.Sc Nursing", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["10 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "oxford-college-of-engineering-management",
    name: "Oxford College of Engineering & Management",
    state: "Bihar",
    city: "Patna",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["5 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "parul-university",
    name: "Parul University",
    state: "Gujarat",
    city: "Vadodara",
    naac: "A+",
    bsccEligible: true,
    featured: true,
    courses: ["B.Pharma", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA", "MBBS India"],
    fees: "From ₹1,20,000/year",
    highlights: ["200+ programs", "International tie-ups", "BSCC Eligible"],
    website: "https://paruluniversity.ac.in",
  },
  {
    id: "pimpri-chinchwad-university",
    name: "Pimpri Chinchwad University",
    state: "Maharashtra",
    city: "Pune",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["6 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "quantum-university",
    name: "Quantum University",
    state: "Uttarakhand",
    city: "Roorkee",
    naac: "A",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Sc Agriculture", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "From ₹1,10,000/year",
    highlights: ["NAAC A accredited", "Industry-focused curriculum", "BSCC Eligible"],
  },
  {
    id: "rit-roorkee-institute-of-technology",
    name: "RIT – Roorkee Institute of Technology",
    state: "Uttarakhand",
    city: "Roorkee",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["9 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "ritee-raipur-institute-of-technology-eng",
    name: "RITEE – Raipur Institute of Technology, Engineering and Economics",
    state: "Chhattisgarh",
    city: "Raipur",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["6 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "rv-group-of-institutions",
    name: "RV Group of Institutions",
    state: "Karnataka",
    city: "Bangalore",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["6 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "rabindranath-tagore-university",
    name: "Rabindranath Tagore University",
    state: "MP",
    city: "Bhopal",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Pharma", "B.Sc Agriculture", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["8 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "rungta-college-of-engineering-technology",
    name: "Rungta College of Engineering & Technology",
    state: "Chhattisgarh",
    city: "Bhilai",
    naac: "A",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Tech / Engineering", "BBA", "LLB", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["11 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "sage-university",
    name: "SAGE University",
    state: "MP",
    city: "Bhopal",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Pharma", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["8 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "sgt-university",
    name: "SGT University",
    state: "Haryana",
    city: "Gurugram",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Pharma", "B.Sc Nursing", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA", "MBBS India"],
    fees: "Consult CAE for fees",
    highlights: ["10 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "sns-vidyapeeth",
    name: "SNS Vidyapeeth",
    state: "Bihar",
    city: "Motihari",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["4 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "sr-university",
    name: "SR University",
    state: "Telangana",
    city: "Warangal",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["6 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "srm-university-delhi-ncr",
    name: "SRM University Delhi-NCR",
    state: "Haryana",
    city: "Sonepat",
    naac: "A+",
    bsccEligible: true,
    featured: true,
    courses: ["B.Sc Agriculture", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "₹3,00,000/year (B.Tech CSE)",
    highlights: ["NAAC A+ rated", "B.Tech Civil/ECE/ME: ₹1,75,000/year", "BSCC Eligible"],
  },
  {
    id: "sandeep-university",
    name: "Sandeep University",
    state: "Bihar",
    city: "Madhubani",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["6 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "sandip-university",
    name: "Sandip University",
    state: "Maharashtra",
    city: "Nashik",
    naac: "A",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Sc Nursing", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "From ₹1,00,000/year",
    highlights: ["B.Tech from ₹1,00,000/year", "MBA and MCA available", "BSCC Eligible"],
  },
  {
    id: "shivalik-college-of-engineering",
    name: "Shivalik College of Engineering",
    state: "Uttarakhand",
    city: "Dehradun",
    naac: "A+",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Sc Agriculture", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["7 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "shobhit-university",
    name: "Shobhit University",
    state: "UP",
    city: "Meerut",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Pharma", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["7 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "shriram-group-of-institutions",
    name: "Shriram Group of Institutions",
    state: "UP",
    city: "Muzaffarnagar",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["6 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "subharti-university",
    name: "Subharti University",
    state: "UP",
    city: "Meerut",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Pharma", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA", "MBBS India"],
    fees: "Consult CAE for fees",
    highlights: ["9 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "suresh-gyan-vihar-university",
    name: "Suresh Gyan Vihar University",
    state: "Rajasthan",
    city: "Jaipur",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Pharma", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["7 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "tit-group",
    name: "TIT Group",
    state: "MP",
    city: "Bhopal",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Tech / Engineering", "BCA/MCA", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["5 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
  {
    id: "teerthanker-mahaveer-university-tmu",
    name: "Teerthanker Mahaveer University (TMU)",
    state: "UP",
    city: "Moradabad",
    naac: "A+",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA", "MBBS India"],
    fees: "Consult CAE for fees",
    highlights: ["9 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "tulas-institute",
    name: "Tulas Institute",
    state: "Uttarakhand",
    city: "Dehradun",
    naac: "A",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Sc Agriculture", "B.Tech / Engineering", "BBA", "BCA/MCA", "MBA"],
    fees: "From ₹2,03,750/year (B.Tech CSE)",
    highlights: ["Merit Scholarship up to ₹10,000", "B.Pharma from ₹1,17,500/year", "BSCC Eligible"],
  },
  {
    id: "uttaranchal-university",
    name: "Uttaranchal University",
    state: "Uttarakhand",
    city: "Dehradun",
    naac: "-",
    bsccEligible: true,
    featured: false,
    courses: ["B.Pharma", "B.Sc Nursing", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["10 courses available", "Direct admission — no entrance test", "BSCC Loan eligible"],
  },
  {
    id: "vignan-s-group-of-institutions",
    name: "Vignan's Group of Institutions",
    state: "Andhra Pradesh",
    city: "Guntur",
    naac: "A",
    bsccEligible: true,
    featured: true,
    courses: ["B.Tech / Engineering", "BCA/MCA", "MBA"],
    fees: "From ₹90,000/year",
    highlights: ["Strong South India presence", "Multiple campuses", "BSCC Eligible"],
  },
  {
    id: "vivekananda-global-university",
    name: "Vivekananda Global University",
    state: "Rajasthan",
    city: "Jaipur",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["B.Pharma", "B.Tech / Engineering", "BBA", "BCA/MCA", "LLB", "MBA"],
    fees: "Consult CAE for fees",
    highlights: ["8 courses available", "Direct admission — no entrance test", "Recognized University"],
  },
]

export const DOMESTIC_LOCATIONS: string[] = [
  'All Locations',
  "Aligarh",
  "Ambala",
  "Amritsar",
  "Bangalore",
  "Bareilly",
  "Bathinda",
  "Bettiah",
  "Bhilai",
  "Bhopal",
  "Bhubaneswar",
  "Chittorgarh",
  "Dehradun",
  "Delhi",
  "Faridabad",
  "Greater Noida",
  "Guntur",
  "Gurugram",
  "Hajipur",
  "Jaipur",
  "Kolkata",
  "Lucknow",
  "Ludhiana",
  "Madhubani",
  "Mandi Gobindgarh",
  "Mathura",
  "Meerut",
  "Mehsana",
  "Moradabad",
  "Motihari",
  "Muzaffarnagar",
  "Nashik",
  "Patna",
  "Phagwara",
  "Pune",
  "Raipur",
  "Rajkot",
  "Rohtak",
  "Roorkee",
  "Sangrur",
  "Siddhpur",
  "Sonepat",
  "Vadodara",
  "Vaishali",
  "Vijayawada",
  "Visakhapatnam",
  "Warangal",
  "Wardha",
]

export const MBBS_ABROAD_COUNTRIES: string[] = [
  "Russia",
  "Kyrgyzstan",
  "Kazakhstan",
  "Uzbekistan",
  "Bangladesh",
  "Nepal",
]

const ABROAD_HIGHLIGHTS = [
  "NMC & WHO Approved University",
  "English Medium Teaching",
  "FMGE/NEXT Coaching Support by CAE",
  "End-to-End Visa & Travel Assistance",
]

export const MBBS_ABROAD_COLLEGES: College[] = [
  // ── Kyrgyzstan (9) ──────────────────────────────────────────────────────
  {
    id: "jalalabad-state-medical-university",
    name: "Jalalabad State Medical University",
    city: "Jalalabad",
    state: "Kyrgyzstan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 4200 USD · Hostel: 600 USD · Mess: 1200 USD",
    hostel: "600 USD",
    mess: "1200 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "osh-state-medical-university",
    name: "Osh State Medical University",
    city: "Osh",
    state: "Kyrgyzstan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 4000 USD · Hostel: 600 USD · Mess: 1200 USD",
    hostel: "600 USD",
    mess: "1200 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "asian-state-medical-university",
    name: "Asian State Medical University",
    city: "Kant",
    state: "Kyrgyzstan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3400 USD · Hostel: 600 USD · Mess: 1200 USD",
    hostel: "600 USD",
    mess: "1200 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "jalalabad-international-university",
    name: "Jalalabad International University",
    city: "Jalalabad",
    state: "Kyrgyzstan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3500 USD · Hostel: 600 USD · Mess: 1200 USD",
    hostel: "600 USD",
    mess: "1200 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "osh-international-university",
    name: "Osh International University",
    city: "Osh",
    state: "Kyrgyzstan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3500 USD · Hostel: 600 USD · Mess: 1200 USD",
    hostel: "600 USD",
    mess: "1200 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "central-international-university",
    name: "Central International University",
    city: "Jalalabad",
    state: "Kyrgyzstan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3200 USD · Hostel: 600 USD · Mess: 1200 USD",
    hostel: "600 USD",
    mess: "1200 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "university-of-south-asia",
    name: "University of South Asia",
    city: "Tokmok",
    state: "Kyrgyzstan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3500 USD · Hostel: 600 USD · Mess: 1200 USD",
    hostel: "600 USD",
    mess: "1200 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "kyrgyz-international-university",
    name: "Kyrgyz International University",
    city: "Bishkek",
    state: "Kyrgyzstan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3200 USD · Hostel: 600 USD · Mess: 1200 USD",
    hostel: "600 USD",
    mess: "1200 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "bishkek-international-medical-university",
    name: "Bishkek International Medical University",
    city: "Bishkek",
    state: "Kyrgyzstan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3500 USD · Hostel: 600 USD · Mess: 1200 USD",
    hostel: "600 USD",
    mess: "1200 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },

  // ── Kazakhstan (8) ──────────────────────────────────────────────────────
  {
    id: "kazakh-national-medical-university",
    name: "Kazakh National Medical University",
    city: "Almaty",
    state: "Kazakhstan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 6000 USD · Hostel: 1200 USD · Mess: 1300 USD",
    hostel: "1200 USD",
    mess: "1300 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "south-kazakhstan-medical-academy",
    name: "South Kazakhstan Medical Academy",
    city: "Shymkent",
    state: "Kazakhstan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 4400 USD · Hostel: 800 USD · Mess: 1200 USD",
    hostel: "800 USD",
    mess: "1200 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "al-farabi-kazakh-national-university",
    name: "Al-Farabi Kazakh National University",
    city: "Almaty",
    state: "Kazakhstan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 5000 USD · Hostel: 800 USD · Mess: 1400 USD",
    hostel: "800 USD",
    mess: "1400 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "astana-state-medical-university",
    name: "Astana State Medical University",
    city: "Astana",
    state: "Kazakhstan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 5500 USD · Hostel: 2000 USD · Mess: 1200 USD",
    hostel: "2000 USD",
    mess: "1200 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "caspian-state-medical-university",
    name: "Caspian State Medical University",
    city: "Almaty",
    state: "Kazakhstan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 4500 USD · Hostel: 800 USD · Mess: 1400 USD",
    hostel: "800 USD",
    mess: "1400 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "kokshetau-state-medical-university",
    name: "Kokshetau State Medical University",
    city: "Kokshetau",
    state: "Kazakhstan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3800 USD · Hostel: 700 USD · Mess: 1200 USD",
    hostel: "700 USD",
    mess: "1200 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "west-kazakhstan-medical-university",
    name: "West Kazakhstan Medical University",
    city: "Aktobe",
    state: "Kazakhstan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 4200 USD · Hostel: 500 USD · Mess: 1200 USD",
    hostel: "500 USD",
    mess: "1200 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "kazakh-russian-medical-university",
    name: "Kazakh Russian Medical University",
    city: "Almaty",
    state: "Kazakhstan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 4500 USD · Hostel: 1000 USD · Mess: 1200 USD",
    hostel: "1000 USD",
    mess: "1200 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },

  // ── Russia (14) ─────────────────────────────────────────────────────────
  {
    id: "yaroslavl-state-medical-university",
    name: "Yaroslavl State Medical University",
    city: "Yaroslavl",
    state: "Russia",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3,50,000 RUB · Hostel: 90,000 RUB · Mess: 1,10,400 RUB",
    hostel: "90,000 RUB",
    mess: "1,10,400 RUB",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "kemerovo-state-medical-university",
    name: "Kemerovo State Medical University",
    city: "Kemerovo",
    state: "Russia",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 2,95,000 RUB · Hostel: 18,000 RUB · Mess: 1,10,400 RUB",
    hostel: "18,000 RUB",
    mess: "1,10,400 RUB",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "northern-state-medical-university",
    name: "Northern State Medical University",
    city: "Arkhangelsk",
    state: "Russia",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3,20,000 RUB · Hostel: 20,000 RUB · Mess: 1,10,400 RUB",
    hostel: "20,000 RUB",
    mess: "1,10,400 RUB",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "tula-state-university",
    name: "Tula State University",
    city: "Tula",
    state: "Russia",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Consult CAE for fees",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "omsk-state-university",
    name: "Omsk State University",
    city: "Omsk",
    state: "Russia",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3,30,000 RUB · Hostel: 20,000 RUB · Mess: 1,10,400 RUB",
    hostel: "20,000 RUB",
    mess: "1,10,400 RUB",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "tver-state-university",
    name: "Tver State University",
    city: "Tver",
    state: "Russia",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 4,30,000 RUB · Hostel: 80,000 RUB · Mess: 1,10,400 RUB",
    hostel: "80,000 RUB",
    mess: "1,10,400 RUB",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "kuban-state-university",
    name: "Kuban State University",
    city: "Krasnodar",
    state: "Russia",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 4,82,000 RUB · Hostel: 80,000 RUB · Mess: 1,10,400 RUB",
    hostel: "80,000 RUB",
    mess: "1,10,400 RUB",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "mari-state-university",
    name: "Mari State University",
    city: "Mari",
    state: "Russia",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 5000 USD · Mess: 1,38,000 RUB",
    mess: "1,38,000 RUB",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "orel-state-university",
    name: "Orel State University",
    city: "Orel",
    state: "Russia",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3,15,750 RUB · Hostel: 55,200 RUB · Mess: 1,10,400 RUB",
    hostel: "55,200 RUB",
    mess: "1,10,400 RUB",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "astrakhan-state-medical-university",
    name: "Astrakhan State Medical University",
    city: "Astrakhan",
    state: "Russia",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3,30,000 RUB · Hostel: 70,000 RUB · Mess: 1,10,400 RUB",
    hostel: "70,000 RUB",
    mess: "1,10,400 RUB",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "ural-state-medical-university",
    name: "Ural State Medical University",
    city: "Yekaterinburg",
    state: "Russia",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3,00,000 RUB · Hostel: 12,000 RUB · Mess: 1,10,400 RUB",
    hostel: "12,000 RUB",
    mess: "1,10,400 RUB",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "tambov-state-university",
    name: "Tambov State University",
    city: "Tambov",
    state: "Russia",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3,850 USD · Hostel: 64,400 RUB · Mess: 1,10,400 RUB",
    hostel: "64,400 RUB",
    mess: "1,10,400 RUB",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "rostov-state-medical-university",
    name: "Rostov State Medical University",
    city: "Rostov",
    state: "Russia",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3,26,000 RUB · Hostel: 27,600 RUB · Mess: 1,10,400 RUB",
    hostel: "27,600 RUB",
    mess: "1,10,400 RUB",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "pskov-state-university",
    name: "Pskov State University",
    city: "Pskov",
    state: "Russia",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 4,000 USD · Mess: 1,38,000 RUB",
    mess: "1,38,000 RUB",
    highlights: ABROAD_HIGHLIGHTS,
  },

  // ── Uzbekistan (4) ──────────────────────────────────────────────────────
  {
    id: "andijan-state-medical-institute",
    name: "Andijan State Medical Institute",
    city: "Andijan",
    state: "Uzbekistan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3500 USD · Hostel: 500 USD · Mess: 1200 USD",
    hostel: "500 USD",
    mess: "1200 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "bukhara-state-medical-institute",
    name: "Bukhara State Medical Institute",
    city: "Bukhara",
    state: "Uzbekistan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3500 USD · Hostel: 500 USD · Mess: 1200 USD",
    hostel: "500 USD",
    mess: "1200 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "fergana-state-medical-institute",
    name: "Fergana State Medical Institute of Public Health",
    city: "Fergana",
    state: "Uzbekistan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3500 USD · Hostel: 500 USD · Mess: 1200 USD",
    hostel: "500 USD",
    mess: "1200 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
  {
    id: "namangan-state-university",
    name: "Namangan State University",
    city: "Namangan",
    state: "Uzbekistan",
    naac: "-",
    bsccEligible: false,
    featured: false,
    courses: ["MBBS Abroad"],
    fees: "Tuition: 3500 USD · Hostel: 500 USD · Mess: 1200 USD",
    hostel: "500 USD",
    mess: "1200 USD",
    highlights: ABROAD_HIGHLIGHTS,
  },
]

// Merge abroad colleges into the main COLLEGES array
COLLEGES.push(...MBBS_ABROAD_COLLEGES)
